import { signIn, signOut, useSession } from "next-auth/react";

import Head from "next/head";
import Image from "next/image";
import sausage from "../res/images/sausage.gif";

export default function Home() {
  const { data: session } = useSession();
  if (session) {
    return (
      <>
        Signed in as {session.user.email} <br />
        <button onClick={() => signOut()}>Sign out</button>
      </>
    );
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="center">
        <h1>SSO6</h1>
        <div>
          <Image src={sausage} alt="sausage logo" />
          <Image src={sausage} alt="sausage logo" />
          <Image src={sausage} alt="sausage logo" />
        </div>
        <>
          Not signed in <br />
          <button onClick={() => signIn()}>Sign in</button>
        </>
        <div>
          <Image src={sausage} alt="sausage logo" />
          <Image src={sausage} alt="sausage logo" />
          <Image src={sausage} alt="sausage logo" />
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
