import Head from "next/head";
import Image from "next/image";
import sausage from "../res/images/sausage.gif";
import styles from "../res/styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main class="center">
        <h1>SSO6</h1>
        <div>
          <Image src={sausage} alt="sausage logo" />
          <Image src={sausage} alt="sausage logo" />
          <Image src={sausage} alt="sausage logo" />
        </div>
        <div>
          <Image src={sausage} alt="sausage logo" />
          <Image src={sausage} alt="sausage logo" />
          <Image src={sausage} alt="sausage logo" />
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
