import { signIn, signOut, useSession } from "next-auth/react";

import Head from "next/head";
import Image from "next/image";
import sausage from "../res/images/sausage.gif";

export default function Home() {
  const { data: session } = useSession();
  const sausageImage = {
    objectFit: "contain",
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="center">
        <h1>SSO6</h1>
        <div className="row">
          <Image src={sausage} alt="sausage logo" {...sausageImage} />
          <Image src={sausage} alt="sausage logo" {...sausageImage} />
          <Image src={sausage} alt="sausage logo" {...sausageImage} />
        </div>
        {session ? (
          <>
            Signed in as {session.user.email} <br />
            <button className="button" onClick={() => signOut()}>
              Sign out
            </button>
          </>
        ) : (
          <>
            Not signed in <br />
            <button className="button" onClick={() => signIn()}>
              Sign in
            </button>
          </>
        )}
        <div className="row">
          <Image src={sausage} alt="sausage logo" {...sausageImage} />
          <Image src={sausage} alt="sausage logo" {...sausageImage} />
          <Image src={sausage} alt="sausage logo" {...sausageImage} />
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
